### ISSUE TITLE
1.12.2 - <Describe Bug>

### ISSUE THREAD

**Issue by NinaCMercer** [Mrbt0907/The-Engender-Mod#3]
**Describe the bug**
The game seemingly returns an entity that doesn't exist. Making minecraft shit itself and freeze, forcing you to close it via task manager, or some linux or mac equivalent.

This crash report could also just be from me killing the game in system monitor, and be unrelated to the freeze, if so then i'll have to attach a log.

**To Reproduce**
1. Install Engender off curseforge, mayhaps with the other mods mentioned in the log in case there's some kind of conflict.
2. Run the game and start spawning wither storms, abominable snow golems, etc. Friendly ones, might I add.
3. Continue doing so until the game freezes.
4. Do ctrl + alt + delete to open task manager, and kill the game. Then check the crash log.

**Logs and/or Screenshots**
[crash-2024-09-16_18.58.54-server.txt](https://github.com/user-attachments/files/17023211/crash-2024-09-16_18.58.54-server.txt)

**Comment by Mrbt0907** [comment]
That bug should be fixed for the next update.
